/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package invoiceGenerator.view;

import invoiceGenerator.controller.CustomerHandler;
import invoiceGenerator.model.Customer;
import invoiceGenerator.util.InvoiceGeneratorException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author tnebes
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        setTitle(Application.APPLICATION_TITLE + " " + Application.operator.getFirstLastName());
        new MyTime().start();
        
    }
 
    private class MyTime extends Thread {

        private SimpleDateFormat simpleDateFormat = new SimpleDateFormat("MMM dd YYYY HH:mm:ss '- week 'ww");
        
        @Override
        public void run() {
            while (true) {
                lblTimeLabel.setText(simpleDateFormat.format(new Date()));
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabController = new javax.swing.JTabbedPane();
        jpRegisterTab = new javax.swing.JPanel();
        customerScrollPane = new javax.swing.JScrollPane();
        customerTextArea = new javax.swing.JTextArea();
        addCustomerButton = new javax.swing.JButton();
        removeCustomerButton = new javax.swing.JButton();
        shippingScrollPane = new javax.swing.JScrollPane();
        shippingTextArea = new javax.swing.JTextArea();
        addCustomerButton1 = new javax.swing.JButton();
        removeCustomerButton1 = new javax.swing.JButton();
        printInvoiceButton = new javax.swing.JButton();
        jpAccountingTab = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        invoicePanel = new javax.swing.JPanel();
        customerPanel = new javax.swing.JPanel();
        jspCustomerScrollPane = new javax.swing.JScrollPane();
        lstCustomerList = new javax.swing.JList<>();
        lblIDLabel = new javax.swing.JLabel();
        lblDateAddedLabel = new javax.swing.JLabel();
        lblNationalIDNumberLabel = new javax.swing.JLabel();
        lblFirstNameLabel = new javax.swing.JLabel();
        lblMiddleNameLabel = new javax.swing.JLabel();
        lblLastNameLabel = new javax.swing.JLabel();
        lblNameLabel = new javax.swing.JLabel();
        lblVATIDLabel = new javax.swing.JLabel();
        lblCustomerTypeLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtpNationalIdNumberTextPane = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtpDateAddedTextPane = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        jtpFirstNameTextPane = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtpMiddleNameTextPane = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jtpLastNameTextPane = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        jtpNameTextPane = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        jtpVATIDTextPane = new javax.swing.JTextPane();
        jcbCustomerTypeCheckBox = new javax.swing.JCheckBox();
        btnCustomerDeleteButton = new javax.swing.JButton();
        btnCustomerSaveButton = new javax.swing.JButton();
        btnCustomerRevertButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtpIdTextPane = new javax.swing.JTextPane();
        articlePanel = new javax.swing.JPanel();
        addressPanel = new javax.swing.JPanel();
        jpOptionsTab = new javax.swing.JPanel();
        databasePanel = new javax.swing.JPanel();
        databaseLabel = new javax.swing.JLabel();
        refreshDatabaseButton = new javax.swing.JButton();
        purgeDatabaseButton = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        lblTimeLabel = new javax.swing.JLabel();
        jmbFileInfoBar = new javax.swing.JMenuBar();
        jmFile = new javax.swing.JMenu();
        jmiExampleItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabController.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jpRegisterTab.setPreferredSize(new java.awt.Dimension(800, 500));

        customerTextArea.setEditable(false);
        customerTextArea.setColumns(20);
        customerTextArea.setRows(5);
        customerScrollPane.setViewportView(customerTextArea);

        addCustomerButton.setText("Add Customer");
        addCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerButtonActionPerformed(evt);
            }
        });

        removeCustomerButton.setText("Remove");
        removeCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCustomerButtonActionPerformed(evt);
            }
        });

        shippingTextArea.setEditable(false);
        shippingTextArea.setColumns(20);
        shippingTextArea.setRows(5);
        shippingScrollPane.setViewportView(shippingTextArea);

        addCustomerButton1.setText("Add Shipping");
        addCustomerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerButton1ActionPerformed(evt);
            }
        });

        removeCustomerButton1.setText("Remove");
        removeCustomerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCustomerButton1ActionPerformed(evt);
            }
        });

        printInvoiceButton.setText("Print Invoice");
        printInvoiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printInvoiceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpRegisterTabLayout = new javax.swing.GroupLayout(jpRegisterTab);
        jpRegisterTab.setLayout(jpRegisterTabLayout);
        jpRegisterTabLayout.setHorizontalGroup(
            jpRegisterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRegisterTabLayout.createSequentialGroup()
                .addGroup(jpRegisterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpRegisterTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpRegisterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(customerScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpRegisterTabLayout.createSequentialGroup()
                                .addComponent(addCustomerButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(removeCustomerButton)))
                        .addGap(35, 35, 35)
                        .addGroup(jpRegisterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(shippingScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpRegisterTabLayout.createSequentialGroup()
                                .addComponent(addCustomerButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(removeCustomerButton1))))
                    .addGroup(jpRegisterTabLayout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(printInvoiceButton)))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        jpRegisterTabLayout.setVerticalGroup(
            jpRegisterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRegisterTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpRegisterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpRegisterTabLayout.createSequentialGroup()
                        .addComponent(customerScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpRegisterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addCustomerButton)
                            .addComponent(removeCustomerButton)))
                    .addGroup(jpRegisterTabLayout.createSequentialGroup()
                        .addComponent(shippingScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpRegisterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addCustomerButton1)
                            .addComponent(removeCustomerButton1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 240, Short.MAX_VALUE)
                .addComponent(printInvoiceButton)
                .addContainerGap())
        );

        tabController.addTab("Register", jpRegisterTab);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerPanelClicked(evt);
            }
        });

        javax.swing.GroupLayout invoicePanelLayout = new javax.swing.GroupLayout(invoicePanel);
        invoicePanel.setLayout(invoicePanelLayout);
        invoicePanelLayout.setHorizontalGroup(
            invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        invoicePanelLayout.setVerticalGroup(
            invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Invoice", invoicePanel);

        lstCustomerList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstCustomerList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCustomerListValueChanged(evt);
            }
        });
        jspCustomerScrollPane.setViewportView(lstCustomerList);

        lblIDLabel.setText("ID:");

        lblDateAddedLabel.setText("Date added:");

        lblNationalIDNumberLabel.setText("National ID number:");

        lblFirstNameLabel.setText("First name:");

        lblMiddleNameLabel.setText("Middle Name:");
        lblMiddleNameLabel.setPreferredSize(null);

        lblLastNameLabel.setText("Last Name:");
        lblLastNameLabel.setPreferredSize(null);

        lblNameLabel.setText("Name:");
        lblNameLabel.setPreferredSize(null);

        lblVATIDLabel.setText("VAT ID");
        lblVATIDLabel.setPreferredSize(null);

        lblCustomerTypeLabel.setText("Type:");
        lblCustomerTypeLabel.setPreferredSize(null);

        jScrollPane2.setViewportView(jtpNationalIdNumberTextPane);

        jtpDateAddedTextPane.setEnabled(false);
        jScrollPane3.setViewportView(jtpDateAddedTextPane);

        jScrollPane8.setViewportView(jtpFirstNameTextPane);

        jScrollPane5.setViewportView(jtpMiddleNameTextPane);

        jScrollPane6.setViewportView(jtpLastNameTextPane);

        jScrollPane7.setViewportView(jtpNameTextPane);

        jScrollPane9.setViewportView(jtpVATIDTextPane);

        jcbCustomerTypeCheckBox.setText("Legal entity?");
        jcbCustomerTypeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCustomerTypeCheckBoxActionPerformed(evt);
            }
        });

        btnCustomerDeleteButton.setText("Delete");
        btnCustomerDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerDeleteButtonActionPerformed(evt);
            }
        });

        btnCustomerSaveButton.setText("Save");
        btnCustomerSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerSaveButtonActionPerformed(evt);
            }
        });

        btnCustomerRevertButton.setText("Revert");
        btnCustomerRevertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerRevertButtonActionPerformed(evt);
            }
        });

        jtpIdTextPane.setEnabled(false);
        jScrollPane4.setViewportView(jtpIdTextPane);

        javax.swing.GroupLayout customerPanelLayout = new javax.swing.GroupLayout(customerPanel);
        customerPanel.setLayout(customerPanelLayout);
        customerPanelLayout.setHorizontalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspCustomerScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addComponent(lblIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerPanelLayout.createSequentialGroup()
                        .addComponent(btnCustomerSaveButton)
                        .addGap(18, 18, 18)
                        .addComponent(btnCustomerRevertButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCustomerDeleteButton))
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblNationalIDNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDateAddedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFirstNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane8)))
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addComponent(lblMiddleNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE))
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addComponent(lblLastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE))
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addComponent(lblNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE))
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVATIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCustomerTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(customerPanelLayout.createSequentialGroup()
                                .addComponent(jcbCustomerTypeCheckBox)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE))))
                .addContainerGap())
        );
        customerPanelLayout.setVerticalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDateAddedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(lblNationalIDNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerPanelLayout.createSequentialGroup()
                                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerPanelLayout.createSequentialGroup()
                                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerPanelLayout.createSequentialGroup()
                                                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerPanelLayout.createSequentialGroup()
                                                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(lblFirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lblMiddleNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(lblLastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(lblNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lblVATIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCustomerTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbCustomerTypeCheckBox))
                        .addGap(77, 77, 77)
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCustomerDeleteButton)
                            .addComponent(btnCustomerSaveButton)
                            .addComponent(btnCustomerRevertButton)))
                    .addComponent(jspCustomerScrollPane))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Customer", customerPanel);

        javax.swing.GroupLayout articlePanelLayout = new javax.swing.GroupLayout(articlePanel);
        articlePanel.setLayout(articlePanelLayout);
        articlePanelLayout.setHorizontalGroup(
            articlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        articlePanelLayout.setVerticalGroup(
            articlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Article", articlePanel);

        javax.swing.GroupLayout addressPanelLayout = new javax.swing.GroupLayout(addressPanel);
        addressPanel.setLayout(addressPanelLayout);
        addressPanelLayout.setHorizontalGroup(
            addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        addressPanelLayout.setVerticalGroup(
            addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Address", addressPanel);

        javax.swing.GroupLayout jpAccountingTabLayout = new javax.swing.GroupLayout(jpAccountingTab);
        jpAccountingTab.setLayout(jpAccountingTabLayout);
        jpAccountingTabLayout.setHorizontalGroup(
            jpAccountingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jpAccountingTabLayout.setVerticalGroup(
            jpAccountingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        tabController.addTab("Accounting", jpAccountingTab);

        databasePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        databaseLabel.setText("Database");

        refreshDatabaseButton.setText("Refresh database");

        purgeDatabaseButton.setText("Purge database");
        purgeDatabaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purgeDatabaseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout databasePanelLayout = new javax.swing.GroupLayout(databasePanel);
        databasePanel.setLayout(databasePanelLayout);
        databasePanelLayout.setHorizontalGroup(
            databasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(databasePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(databasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(databaseLabel)
                    .addComponent(refreshDatabaseButton)
                    .addComponent(purgeDatabaseButton))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        databasePanelLayout.setVerticalGroup(
            databasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(databasePanelLayout.createSequentialGroup()
                .addComponent(databaseLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(refreshDatabaseButton)
                .addGap(18, 18, 18)
                .addComponent(purgeDatabaseButton)
                .addGap(0, 130, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpOptionsTabLayout = new javax.swing.GroupLayout(jpOptionsTab);
        jpOptionsTab.setLayout(jpOptionsTabLayout);
        jpOptionsTabLayout.setHorizontalGroup(
            jpOptionsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpOptionsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(databasePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(568, Short.MAX_VALUE))
        );
        jpOptionsTabLayout.setVerticalGroup(
            jpOptionsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpOptionsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(databasePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(279, Short.MAX_VALUE))
        );

        tabController.addTab("Options", jpOptionsTab);

        jToolBar1.setRollover(true);

        lblTimeLabel.setText("time");
        jToolBar1.add(lblTimeLabel);

        jmFile.setText("File");

        jmiExampleItem.setText("Example");
        jmFile.add(jmiExampleItem);

        jmbFileInfoBar.add(jmFile);

        jMenu2.setText("Info");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jmbFileInfoBar.add(jMenu2);

        setJMenuBar(jmbFileInfoBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabController)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabController, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCustomerButtonActionPerformed

    private void removeCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCustomerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeCustomerButtonActionPerformed

    private void addCustomerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCustomerButton1ActionPerformed

    private void removeCustomerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCustomerButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeCustomerButton1ActionPerformed

    private void printInvoiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printInvoiceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printInvoiceButtonActionPerformed

    private void purgeDatabaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purgeDatabaseButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purgeDatabaseButtonActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        Date date = new Date();
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("YYYY");
        JOptionPane.showMessageDialog(rootPane, "This program has been made by Tomislav Nebes.\n2020 - " + simpleDateFormat.format(date));
    }//GEN-LAST:event_jMenu2MouseClicked

    private void CustomerPanelClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerPanelClicked
        loadCustomers();
    }//GEN-LAST:event_CustomerPanelClicked

    private void lstCustomerListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCustomerListValueChanged
        // TODO what does this do?
        if (evt.getValueIsAdjusting()) {
            return;
        }
        
        Customer customer = lstCustomerList.getSelectedValue();
        if (customer == null) {
            return;
        }
        
        updateCustomerTextPanes(customer);
    }//GEN-LAST:event_lstCustomerListValueChanged

    private void jcbCustomerTypeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCustomerTypeCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbCustomerTypeCheckBoxActionPerformed

    private void btnCustomerDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerDeleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCustomerDeleteButtonActionPerformed

    private void btnCustomerSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerSaveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCustomerSaveButtonActionPerformed

    private void btnCustomerRevertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerRevertButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCustomerRevertButtonActionPerformed

    /* Customer Panel */
    /* ************** */
    
        private void loadCustomers() {
        CustomerHandler customerHandler = new CustomerHandler();        
        DefaultListModel<Customer> customers = new DefaultListModel<>();
        try {
            customers.addAll(customerHandler.getData());
        } catch (InvoiceGeneratorException e) {
            e.printStackTrace();
        }
        lstCustomerList.setModel(customers);
    }
        
    private void clearCustomerTextPanes() {
        jtpIdTextPane.setText("");
        jtpDateAddedTextPane.setText("");
        jtpNationalIdNumberTextPane.setText("");
        jcbCustomerTypeCheckBox.setSelected(false);
        jtpFirstNameTextPane.setText("");
        jtpMiddleNameTextPane.setText("");
        jtpLastNameTextPane.setText("");
        jtpNameTextPane.setText("");
        jtpVATIDTextPane.setText("");
    }

    private void updateCustomerTextPanes(Customer customer) {
        clearCustomerTextPanes();
        // FIXME a really bad workaround
        jtpIdTextPane.setText("" + customer.getId());
        jtpDateAddedTextPane.setText(customer.getDateOfCreation().toString());
        jtpNationalIdNumberTextPane.setText(customer.getNationalIdNumber());
        jcbCustomerTypeCheckBox.setSelected(customer.isType());
        if (customer.isType() == Customer.NATURAL_PERSON) {
            jtpFirstNameTextPane.setText(customer.getFirstName());
            jtpMiddleNameTextPane.setText(customer.getMiddleName());
            jtpLastNameTextPane.setText(customer.getLastName());
        } else {
            jtpNameTextPane.setText(customer.getName());
            jtpVATIDTextPane.setText(customer.getVATID());
        }
    }
        
    /* ************** */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomerButton;
    private javax.swing.JButton addCustomerButton1;
    private javax.swing.JPanel addressPanel;
    private javax.swing.JPanel articlePanel;
    private javax.swing.JButton btnCustomerDeleteButton;
    private javax.swing.JButton btnCustomerRevertButton;
    private javax.swing.JButton btnCustomerSaveButton;
    private javax.swing.JPanel customerPanel;
    private javax.swing.JScrollPane customerScrollPane;
    private javax.swing.JTextArea customerTextArea;
    private javax.swing.JLabel databaseLabel;
    private javax.swing.JPanel databasePanel;
    private javax.swing.JPanel invoicePanel;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JCheckBox jcbCustomerTypeCheckBox;
    private javax.swing.JMenu jmFile;
    private javax.swing.JMenuBar jmbFileInfoBar;
    private javax.swing.JMenuItem jmiExampleItem;
    private javax.swing.JPanel jpAccountingTab;
    private javax.swing.JPanel jpOptionsTab;
    private javax.swing.JPanel jpRegisterTab;
    private javax.swing.JScrollPane jspCustomerScrollPane;
    private javax.swing.JTextPane jtpDateAddedTextPane;
    private javax.swing.JTextPane jtpFirstNameTextPane;
    private javax.swing.JTextPane jtpIdTextPane;
    private javax.swing.JTextPane jtpLastNameTextPane;
    private javax.swing.JTextPane jtpMiddleNameTextPane;
    private javax.swing.JTextPane jtpNameTextPane;
    private javax.swing.JTextPane jtpNationalIdNumberTextPane;
    private javax.swing.JTextPane jtpVATIDTextPane;
    private javax.swing.JLabel lblCustomerTypeLabel;
    private javax.swing.JLabel lblDateAddedLabel;
    private javax.swing.JLabel lblFirstNameLabel;
    private javax.swing.JLabel lblIDLabel;
    private javax.swing.JLabel lblLastNameLabel;
    private javax.swing.JLabel lblMiddleNameLabel;
    private javax.swing.JLabel lblNameLabel;
    private javax.swing.JLabel lblNationalIDNumberLabel;
    private javax.swing.JLabel lblTimeLabel;
    private javax.swing.JLabel lblVATIDLabel;
    private javax.swing.JList<Customer> lstCustomerList;
    private javax.swing.JButton printInvoiceButton;
    private javax.swing.JButton purgeDatabaseButton;
    private javax.swing.JButton refreshDatabaseButton;
    private javax.swing.JButton removeCustomerButton;
    private javax.swing.JButton removeCustomerButton1;
    private javax.swing.JScrollPane shippingScrollPane;
    private javax.swing.JTextArea shippingTextArea;
    private javax.swing.JTabbedPane tabController;
    // End of variables declaration//GEN-END:variables
}
