/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package invoiceGenerator.view;

import invoiceGenerator.controller.CustomerHandler;
import invoiceGenerator.model.Address;
import invoiceGenerator.model.Article;
import invoiceGenerator.model.Customer;
import invoiceGenerator.util.InvoiceGeneratorException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author tnebes
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        setTitle(Application.APPLICATION_TITLE + " " + Application.operator.getFirstLastName());
        new MyTime().start();
        
    }
 
    private class MyTime extends Thread {

        private SimpleDateFormat simpleDateFormat = new SimpleDateFormat("MMM dd YYYY HH:mm:ss '- week 'ww");
        
        @Override
        public void run() {
            while (true) {
                lblTimeLabel.setText(simpleDateFormat.format(new Date()));
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabController = new javax.swing.JTabbedPane();
        jpRegisterTab = new javax.swing.JPanel();
        customerScrollPane = new javax.swing.JScrollPane();
        customerTextArea = new javax.swing.JTextArea();
        addCustomerButton = new javax.swing.JButton();
        removeCustomerButton = new javax.swing.JButton();
        shippingScrollPane = new javax.swing.JScrollPane();
        shippingTextArea = new javax.swing.JTextArea();
        addCustomerButton1 = new javax.swing.JButton();
        removeCustomerButton1 = new javax.swing.JButton();
        printInvoiceButton = new javax.swing.JButton();
        jpAccountingTab = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        invoicePanel = new javax.swing.JPanel();
        customerPanel = new javax.swing.JPanel();
        jspCustomerScrollPane = new javax.swing.JScrollPane();
        lstCustomerList = new javax.swing.JList<>();
        lblCustomerIDLabel = new javax.swing.JLabel();
        lblCustomerDateAddedLabel = new javax.swing.JLabel();
        lblCustomerNationalIDNumberLabel = new javax.swing.JLabel();
        lblFirstNameLabel = new javax.swing.JLabel();
        lblMiddleNameLabel = new javax.swing.JLabel();
        lblLastNameLabel = new javax.swing.JLabel();
        lblCustomerNameLabel = new javax.swing.JLabel();
        lblVATIDLabel = new javax.swing.JLabel();
        lblCustomerTypeLabel = new javax.swing.JLabel();
        jcbCustomerTypeCheckBox = new javax.swing.JCheckBox();
        btnCustomerDeleteButton = new javax.swing.JButton();
        btnCustomerSaveButton = new javax.swing.JButton();
        btnCustomerRevertButton = new javax.swing.JButton();
        txtCustomerID = new javax.swing.JTextField();
        txtCustomerDateAdded = new javax.swing.JTextField();
        txtCustomerNationalIDNumber = new javax.swing.JTextField();
        txtCustomerFirstName = new javax.swing.JTextField();
        txtCustomerMiddleName = new javax.swing.JTextField();
        txtCustomerLastName = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtCustomerLegalName = new javax.swing.JTextField();
        txtCustomerVATID = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblCustomerAddress = new javax.swing.JLabel();
        btnCustomerBillingAddress = new javax.swing.JButton();
        btnCustomerShippingAddress = new javax.swing.JButton();
        btnCustomerAddCustomer = new javax.swing.JButton();
        articlePanel = new javax.swing.JPanel();
        jspArticleScrollPane = new javax.swing.JScrollPane();
        lstArticleList = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        lblArticleIDLabel = new javax.swing.JLabel();
        lblArticleDateAddedLabel = new javax.swing.JLabel();
        lblArticleShortNameLabel = new javax.swing.JLabel();
        lblArticleWarehouseLocationLabel = new javax.swing.JLabel();
        lblArticleQuantityLabel = new javax.swing.JLabel();
        lblArticleShortDescriptionLabel = new javax.swing.JLabel();
        lblArticleShortDescriptionLabel1 = new javax.swing.JLabel();
        lblArticleLongNameLabel = new javax.swing.JLabel();
        txtArticleID = new javax.swing.JTextField();
        txtArticleDateAdded = new javax.swing.JTextField();
        txtArticleShortName = new javax.swing.JTextField();
        txtArticleQuantity = new javax.swing.JTextField();
        txtArticleWarehouseLocation = new javax.swing.JTextField();
        txtArticleLongName = new javax.swing.JTextField();
        txtArticleShortDescription = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArticleLongDescription = new javax.swing.JTextArea();
        jSeparator3 = new javax.swing.JSeparator();
        lblArticleShortDescriptionLabel2 = new javax.swing.JLabel();
        txtArticleTaxRate = new javax.swing.JTextField();
        lblArticleShortDescriptionLabel3 = new javax.swing.JLabel();
        lblArticleShortDescriptionLabel4 = new javax.swing.JLabel();
        txtArticleWholesalePrice = new javax.swing.JTextField();
        lblArticleShortDescriptionLabel5 = new javax.swing.JLabel();
        txtArticleRetailPrice = new javax.swing.JTextField();
        btnArticleSave = new javax.swing.JButton();
        btnArticleRevert = new javax.swing.JButton();
        btnArticleAdd = new javax.swing.JButton();
        btnArticleDelete = new javax.swing.JButton();
        addressPanel = new javax.swing.JPanel();
        jspArticleScrollPane1 = new javax.swing.JScrollPane();
        lstAddressList = new javax.swing.JList<>();
        jpOptionsTab = new javax.swing.JPanel();
        databasePanel = new javax.swing.JPanel();
        databaseLabel = new javax.swing.JLabel();
        refreshDatabaseButton = new javax.swing.JButton();
        purgeDatabaseButton = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        lblTimeLabel = new javax.swing.JLabel();
        jmbFileInfoBar = new javax.swing.JMenuBar();
        jmFile = new javax.swing.JMenu();
        jmiExampleItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabController.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jpRegisterTab.setPreferredSize(new java.awt.Dimension(800, 500));

        customerTextArea.setEditable(false);
        customerTextArea.setColumns(20);
        customerTextArea.setRows(5);
        customerScrollPane.setViewportView(customerTextArea);

        addCustomerButton.setText("Add Customer");
        addCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerButtonActionPerformed(evt);
            }
        });

        removeCustomerButton.setText("Remove");
        removeCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCustomerButtonActionPerformed(evt);
            }
        });

        shippingTextArea.setEditable(false);
        shippingTextArea.setColumns(20);
        shippingTextArea.setRows(5);
        shippingScrollPane.setViewportView(shippingTextArea);

        addCustomerButton1.setText("Add Shipping");
        addCustomerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerButton1ActionPerformed(evt);
            }
        });

        removeCustomerButton1.setText("Remove");
        removeCustomerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCustomerButton1ActionPerformed(evt);
            }
        });

        printInvoiceButton.setText("Print Invoice");
        printInvoiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printInvoiceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpRegisterTabLayout = new javax.swing.GroupLayout(jpRegisterTab);
        jpRegisterTab.setLayout(jpRegisterTabLayout);
        jpRegisterTabLayout.setHorizontalGroup(
            jpRegisterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRegisterTabLayout.createSequentialGroup()
                .addGroup(jpRegisterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpRegisterTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpRegisterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(customerScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpRegisterTabLayout.createSequentialGroup()
                                .addComponent(addCustomerButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(removeCustomerButton)))
                        .addGap(35, 35, 35)
                        .addGroup(jpRegisterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(shippingScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpRegisterTabLayout.createSequentialGroup()
                                .addComponent(addCustomerButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(removeCustomerButton1))))
                    .addGroup(jpRegisterTabLayout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(printInvoiceButton)))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        jpRegisterTabLayout.setVerticalGroup(
            jpRegisterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRegisterTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpRegisterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpRegisterTabLayout.createSequentialGroup()
                        .addComponent(customerScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpRegisterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addCustomerButton)
                            .addComponent(removeCustomerButton)))
                    .addGroup(jpRegisterTabLayout.createSequentialGroup()
                        .addComponent(shippingScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpRegisterTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addCustomerButton1)
                            .addComponent(removeCustomerButton1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 240, Short.MAX_VALUE)
                .addComponent(printInvoiceButton)
                .addContainerGap())
        );

        tabController.addTab("Register", jpRegisterTab);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerPanelClicked(evt);
            }
        });

        javax.swing.GroupLayout invoicePanelLayout = new javax.swing.GroupLayout(invoicePanel);
        invoicePanel.setLayout(invoicePanelLayout);
        invoicePanelLayout.setHorizontalGroup(
            invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        invoicePanelLayout.setVerticalGroup(
            invoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Invoice", invoicePanel);

        lstCustomerList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstCustomerList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCustomerListValueChanged(evt);
            }
        });
        jspCustomerScrollPane.setViewportView(lstCustomerList);

        lblCustomerIDLabel.setText("ID:");

        lblCustomerDateAddedLabel.setText("Date added:");

        lblCustomerNationalIDNumberLabel.setText("National ID number:");

        lblFirstNameLabel.setText("First name:");

        lblMiddleNameLabel.setText("Middle Name:");
        lblMiddleNameLabel.setPreferredSize(null);

        lblLastNameLabel.setText("Last Name:");
        lblLastNameLabel.setPreferredSize(null);

        lblCustomerNameLabel.setText("Name:");
        lblCustomerNameLabel.setPreferredSize(null);

        lblVATIDLabel.setText("VAT ID");
        lblVATIDLabel.setPreferredSize(null);

        lblCustomerTypeLabel.setText("Type:");
        lblCustomerTypeLabel.setPreferredSize(null);

        jcbCustomerTypeCheckBox.setText("Legal entity?");
        jcbCustomerTypeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCustomerTypeCheckBoxActionPerformed(evt);
            }
        });

        btnCustomerDeleteButton.setText("Delete");
        btnCustomerDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerDeleteButtonActionPerformed(evt);
            }
        });

        btnCustomerSaveButton.setText("Save");
        btnCustomerSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerSaveButtonActionPerformed(evt);
            }
        });

        btnCustomerRevertButton.setText("Revert");
        btnCustomerRevertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerRevertButtonActionPerformed(evt);
            }
        });

        txtCustomerID.setEnabled(false);

        txtCustomerDateAdded.setEnabled(false);

        lblCustomerAddress.setText("Address:");

        btnCustomerBillingAddress.setText("Billing address");
        btnCustomerBillingAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerBillingAddressActionPerformed(evt);
            }
        });

        btnCustomerShippingAddress.setText("Shipping address");
        btnCustomerShippingAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerShippingAddressActionPerformed(evt);
            }
        });

        btnCustomerAddCustomer.setText("Add");
        btnCustomerAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerAddCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customerPanelLayout = new javax.swing.GroupLayout(customerPanel);
        customerPanel.setLayout(customerPanelLayout);
        customerPanelLayout.setHorizontalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspCustomerScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerPanelLayout.createSequentialGroup()
                        .addComponent(btnCustomerSaveButton)
                        .addGap(18, 18, 18)
                        .addComponent(btnCustomerRevertButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCustomerAddCustomer)
                        .addGap(18, 18, 18)
                        .addComponent(btnCustomerDeleteButton))
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblCustomerNationalIDNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblFirstNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblLastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCustomerNationalIDNumber)
                            .addGroup(customerPanelLayout.createSequentialGroup()
                                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCustomerLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(customerPanelLayout.createSequentialGroup()
                                        .addComponent(txtCustomerFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblMiddleNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCustomerMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator1)
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addComponent(lblCustomerIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(lblCustomerDateAddedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(txtCustomerDateAdded, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCustomerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVATIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(104, 104, 104)
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCustomerVATID, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCustomerLegalName)))
                    .addComponent(jSeparator2)
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(customerPanelLayout.createSequentialGroup()
                                .addComponent(lblCustomerTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(111, 111, 111)
                                .addComponent(jcbCustomerTypeCheckBox))
                            .addGroup(customerPanelLayout.createSequentialGroup()
                                .addComponent(lblCustomerAddress)
                                .addGap(18, 18, 18)
                                .addComponent(btnCustomerBillingAddress)
                                .addGap(18, 18, 18)
                                .addComponent(btnCustomerShippingAddress)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        customerPanelLayout.setVerticalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCustomerIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCustomerDateAddedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCustomerDateAdded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCustomerNationalIDNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCustomerNationalIDNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCustomerFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMiddleNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCustomerMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCustomerLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCustomerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCustomerLegalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVATIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCustomerVATID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCustomerTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbCustomerTypeCheckBox))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCustomerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCustomerBillingAddress)
                            .addComponent(btnCustomerShippingAddress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCustomerDeleteButton)
                            .addComponent(btnCustomerSaveButton)
                            .addComponent(btnCustomerRevertButton)
                            .addComponent(btnCustomerAddCustomer)))
                    .addComponent(jspCustomerScrollPane))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Customer", customerPanel);

        articlePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                articlePanelMouseClicked(evt);
            }
        });

        lstArticleList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstArticleList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstArticleListValueChanged(evt);
            }
        });
        jspArticleScrollPane.setViewportView(lstArticleList);

        lblArticleIDLabel.setText("ID:");

        lblArticleDateAddedLabel.setText("Date added:");

        lblArticleShortNameLabel.setText("Short name:");

        lblArticleWarehouseLocationLabel.setText("Warehouse location:");

        lblArticleQuantityLabel.setText("Quantity:");

        lblArticleShortDescriptionLabel.setText("Short Description:");

        lblArticleShortDescriptionLabel1.setText("Long Description:");

        lblArticleLongNameLabel.setText("Long name:");

        txtArticleID.setEditable(false);

        txtArticleDateAdded.setEditable(false);

        txtArticleLongDescription.setColumns(20);
        txtArticleLongDescription.setRows(5);
        jScrollPane2.setViewportView(txtArticleLongDescription);

        lblArticleShortDescriptionLabel2.setText("Tax rate:");

        lblArticleShortDescriptionLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArticleShortDescriptionLabel3.setText("%");
        lblArticleShortDescriptionLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblArticleShortDescriptionLabel4.setText("Wholesale price:");

        lblArticleShortDescriptionLabel5.setText("Retail price:");

        btnArticleSave.setText("Save");
        btnArticleSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArticleSaveActionPerformed(evt);
            }
        });

        btnArticleRevert.setText("Revert");
        btnArticleRevert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArticleRevertActionPerformed(evt);
            }
        });

        btnArticleAdd.setText("Add");
        btnArticleAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArticleAddActionPerformed(evt);
            }
        });

        btnArticleDelete.setText("Delete");
        btnArticleDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArticleDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblArticleWarehouseLocationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtArticleWarehouseLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblArticleShortNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtArticleShortName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblArticleIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtArticleID)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblArticleDateAddedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtArticleDateAdded))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblArticleQuantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtArticleQuantity))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblArticleShortDescriptionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblArticleLongNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtArticleLongName))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblArticleShortDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtArticleShortDescription))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblArticleShortDescriptionLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtArticleRetailPrice))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblArticleShortDescriptionLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtArticleTaxRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblArticleShortDescriptionLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(lblArticleShortDescriptionLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtArticleWholesalePrice, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnArticleSave)
                        .addGap(18, 18, 18)
                        .addComponent(btnArticleRevert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnArticleAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnArticleDelete)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblArticleIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                        .addComponent(txtArticleID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblArticleDateAddedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                        .addComponent(txtArticleDateAdded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblArticleShortNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblArticleQuantityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                        .addComponent(txtArticleShortName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtArticleQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArticleWarehouseLocationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtArticleWarehouseLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArticleLongNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtArticleLongName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArticleShortDescriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtArticleShortDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblArticleShortDescriptionLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                        .addGap(81, 81, 81))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArticleShortDescriptionLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtArticleTaxRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblArticleShortDescriptionLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblArticleShortDescriptionLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtArticleWholesalePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArticleShortDescriptionLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtArticleRetailPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnArticleDelete)
                    .addComponent(btnArticleSave)
                    .addComponent(btnArticleRevert)
                    .addComponent(btnArticleAdd))
                .addContainerGap())
        );

        javax.swing.GroupLayout articlePanelLayout = new javax.swing.GroupLayout(articlePanel);
        articlePanel.setLayout(articlePanelLayout);
        articlePanelLayout.setHorizontalGroup(
            articlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, articlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspArticleScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        articlePanelLayout.setVerticalGroup(
            articlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, articlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(articlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jspArticleScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Article", articlePanel);

        addressPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addressPanelMouseClicked(evt);
            }
        });

        lstAddressList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstAddressList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstAddressListValueChanged(evt);
            }
        });
        jspArticleScrollPane1.setViewportView(lstAddressList);

        javax.swing.GroupLayout addressPanelLayout = new javax.swing.GroupLayout(addressPanel);
        addressPanel.setLayout(addressPanelLayout);
        addressPanelLayout.setHorizontalGroup(
            addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspArticleScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(556, Short.MAX_VALUE))
        );
        addressPanelLayout.setVerticalGroup(
            addressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspArticleScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Address", addressPanel);

        javax.swing.GroupLayout jpAccountingTabLayout = new javax.swing.GroupLayout(jpAccountingTab);
        jpAccountingTab.setLayout(jpAccountingTabLayout);
        jpAccountingTabLayout.setHorizontalGroup(
            jpAccountingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jpAccountingTabLayout.setVerticalGroup(
            jpAccountingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        tabController.addTab("Accounting", jpAccountingTab);

        databasePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        databaseLabel.setText("Database");

        refreshDatabaseButton.setText("Refresh database");

        purgeDatabaseButton.setText("Purge database");
        purgeDatabaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purgeDatabaseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout databasePanelLayout = new javax.swing.GroupLayout(databasePanel);
        databasePanel.setLayout(databasePanelLayout);
        databasePanelLayout.setHorizontalGroup(
            databasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(databasePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(databasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(databaseLabel)
                    .addComponent(refreshDatabaseButton)
                    .addComponent(purgeDatabaseButton))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        databasePanelLayout.setVerticalGroup(
            databasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(databasePanelLayout.createSequentialGroup()
                .addComponent(databaseLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(refreshDatabaseButton)
                .addGap(18, 18, 18)
                .addComponent(purgeDatabaseButton)
                .addGap(0, 130, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpOptionsTabLayout = new javax.swing.GroupLayout(jpOptionsTab);
        jpOptionsTab.setLayout(jpOptionsTabLayout);
        jpOptionsTabLayout.setHorizontalGroup(
            jpOptionsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpOptionsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(databasePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(568, Short.MAX_VALUE))
        );
        jpOptionsTabLayout.setVerticalGroup(
            jpOptionsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpOptionsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(databasePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(279, Short.MAX_VALUE))
        );

        tabController.addTab("Options", jpOptionsTab);

        jToolBar1.setRollover(true);

        lblTimeLabel.setText("time");
        jToolBar1.add(lblTimeLabel);

        jmFile.setText("File");

        jmiExampleItem.setText("Example");
        jmFile.add(jmiExampleItem);

        jmbFileInfoBar.add(jmFile);

        jMenu2.setText("Info");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jmbFileInfoBar.add(jMenu2);

        setJMenuBar(jmbFileInfoBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabController)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabController, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCustomerButtonActionPerformed

    private void removeCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCustomerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeCustomerButtonActionPerformed

    private void addCustomerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCustomerButton1ActionPerformed

    private void removeCustomerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCustomerButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeCustomerButton1ActionPerformed

    private void printInvoiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printInvoiceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printInvoiceButtonActionPerformed

    private void purgeDatabaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purgeDatabaseButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purgeDatabaseButtonActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        Date date = new Date();
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("YYYY");
        JOptionPane.showMessageDialog(rootPane, "This program has been made by Tomislav Nebes.\n2020 - " + simpleDateFormat.format(date));
    }//GEN-LAST:event_jMenu2MouseClicked

    private void CustomerPanelClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerPanelClicked
        loadCustomers();
    }//GEN-LAST:event_CustomerPanelClicked

    private void btnArticleDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArticleDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnArticleDeleteActionPerformed

    private void btnArticleAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArticleAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnArticleAddActionPerformed

    private void btnArticleRevertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArticleRevertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnArticleRevertActionPerformed

    private void btnArticleSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArticleSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnArticleSaveActionPerformed

    private void lstArticleListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstArticleListValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lstArticleListValueChanged

    private void btnCustomerAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerAddCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCustomerAddCustomerActionPerformed

    private void btnCustomerShippingAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerShippingAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCustomerShippingAddressActionPerformed

    private void btnCustomerBillingAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerBillingAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCustomerBillingAddressActionPerformed

    private void btnCustomerRevertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerRevertButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCustomerRevertButtonActionPerformed

    private void btnCustomerSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerSaveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCustomerSaveButtonActionPerformed

    private void btnCustomerDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerDeleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCustomerDeleteButtonActionPerformed

    private void jcbCustomerTypeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCustomerTypeCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbCustomerTypeCheckBoxActionPerformed

    private void lstCustomerListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCustomerListValueChanged
        // TODO what does this do?
        if (evt.getValueIsAdjusting()) {
            return;
        }

        Customer customer = lstCustomerList.getSelectedValue();
        if (customer == null) {
            return;
        }

        updateCustomerTextPanes(customer);
    }//GEN-LAST:event_lstCustomerListValueChanged

    private void lstAddressListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstAddressListValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lstAddressListValueChanged

    private void addressPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addressPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addressPanelMouseClicked

    private void articlePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_articlePanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_articlePanelMouseClicked

    /* Customer Panel */
    /* ************** */
    
    private void loadCustomers() {
        CustomerHandler customerHandler = new CustomerHandler();        
        DefaultListModel<Customer> customers = new DefaultListModel<>();
        try {
            customers.addAll(customerHandler.getData());
        } catch (InvoiceGeneratorException e) {
            e.printStackTrace();
        }  
        lstCustomerList.setModel(customers);
    }
        
    private void clearCustomerTextPanes() {
        txtCustomerID.setText("");
        txtCustomerDateAdded.setText("");
        txtCustomerNationalIDNumber.setText("");
        jcbCustomerTypeCheckBox.setSelected(false);
        txtCustomerFirstName.setText("");
        txtCustomerMiddleName.setText("");
        txtCustomerLastName.setText("");
        txtCustomerLegalName.setText("");
        txtCustomerVATID.setText("");
    }

    private void updateCustomerTextPanes(Customer customer) {
        clearCustomerTextPanes();
        // FIXME a really bad workaround
        txtCustomerID.setText("" + customer.getId());
        txtCustomerDateAdded.setText(customer.getDateOfCreation().toString());
        txtCustomerNationalIDNumber.setText(customer.getNationalIdNumber());
        jcbCustomerTypeCheckBox.setSelected(customer.isType());
        if (customer.isType() == Customer.NATURAL_PERSON) {
            txtCustomerFirstName.setText(customer.getFirstName());
            txtCustomerMiddleName.setText(customer.getMiddleName());
            txtCustomerLastName.setText(customer.getLastName());
        } else {
            txtCustomerLegalName.setText(customer.getName());
            txtCustomerVATID.setText(customer.getVATID());
        }
    }
        
    /* ************** */
    
    /* Article Panel */
    /* ************* */
    
    
    
    /* ************* */

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomerButton;
    private javax.swing.JButton addCustomerButton1;
    private javax.swing.JPanel addressPanel;
    private javax.swing.JPanel articlePanel;
    private javax.swing.JButton btnArticleAdd;
    private javax.swing.JButton btnArticleDelete;
    private javax.swing.JButton btnArticleRevert;
    private javax.swing.JButton btnArticleSave;
    private javax.swing.JButton btnCustomerAddCustomer;
    private javax.swing.JButton btnCustomerBillingAddress;
    private javax.swing.JButton btnCustomerDeleteButton;
    private javax.swing.JButton btnCustomerRevertButton;
    private javax.swing.JButton btnCustomerSaveButton;
    private javax.swing.JButton btnCustomerShippingAddress;
    private javax.swing.JPanel customerPanel;
    private javax.swing.JScrollPane customerScrollPane;
    private javax.swing.JTextArea customerTextArea;
    private javax.swing.JLabel databaseLabel;
    private javax.swing.JPanel databasePanel;
    private javax.swing.JPanel invoicePanel;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JCheckBox jcbCustomerTypeCheckBox;
    private javax.swing.JMenu jmFile;
    private javax.swing.JMenuBar jmbFileInfoBar;
    private javax.swing.JMenuItem jmiExampleItem;
    private javax.swing.JPanel jpAccountingTab;
    private javax.swing.JPanel jpOptionsTab;
    private javax.swing.JPanel jpRegisterTab;
    private javax.swing.JScrollPane jspArticleScrollPane;
    private javax.swing.JScrollPane jspArticleScrollPane1;
    private javax.swing.JScrollPane jspCustomerScrollPane;
    private javax.swing.JLabel lblArticleDateAddedLabel;
    private javax.swing.JLabel lblArticleIDLabel;
    private javax.swing.JLabel lblArticleLongNameLabel;
    private javax.swing.JLabel lblArticleQuantityLabel;
    private javax.swing.JLabel lblArticleShortDescriptionLabel;
    private javax.swing.JLabel lblArticleShortDescriptionLabel1;
    private javax.swing.JLabel lblArticleShortDescriptionLabel2;
    private javax.swing.JLabel lblArticleShortDescriptionLabel3;
    private javax.swing.JLabel lblArticleShortDescriptionLabel4;
    private javax.swing.JLabel lblArticleShortDescriptionLabel5;
    private javax.swing.JLabel lblArticleShortNameLabel;
    private javax.swing.JLabel lblArticleWarehouseLocationLabel;
    private javax.swing.JLabel lblCustomerAddress;
    private javax.swing.JLabel lblCustomerDateAddedLabel;
    private javax.swing.JLabel lblCustomerIDLabel;
    private javax.swing.JLabel lblCustomerNameLabel;
    private javax.swing.JLabel lblCustomerNationalIDNumberLabel;
    private javax.swing.JLabel lblCustomerTypeLabel;
    private javax.swing.JLabel lblFirstNameLabel;
    private javax.swing.JLabel lblLastNameLabel;
    private javax.swing.JLabel lblMiddleNameLabel;
    private javax.swing.JLabel lblTimeLabel;
    private javax.swing.JLabel lblVATIDLabel;
    private javax.swing.JList<Article> lstAddressList;
    private javax.swing.JList<Address> lstArticleList;
    private javax.swing.JList<Customer> lstCustomerList;
    private javax.swing.JButton printInvoiceButton;
    private javax.swing.JButton purgeDatabaseButton;
    private javax.swing.JButton refreshDatabaseButton;
    private javax.swing.JButton removeCustomerButton;
    private javax.swing.JButton removeCustomerButton1;
    private javax.swing.JScrollPane shippingScrollPane;
    private javax.swing.JTextArea shippingTextArea;
    private javax.swing.JTabbedPane tabController;
    private javax.swing.JTextField txtArticleDateAdded;
    private javax.swing.JTextField txtArticleID;
    private javax.swing.JTextArea txtArticleLongDescription;
    private javax.swing.JTextField txtArticleLongName;
    private javax.swing.JTextField txtArticleQuantity;
    private javax.swing.JTextField txtArticleRetailPrice;
    private javax.swing.JTextField txtArticleShortDescription;
    private javax.swing.JTextField txtArticleShortName;
    private javax.swing.JTextField txtArticleTaxRate;
    private javax.swing.JTextField txtArticleWarehouseLocation;
    private javax.swing.JTextField txtArticleWholesalePrice;
    private javax.swing.JTextField txtCustomerDateAdded;
    private javax.swing.JTextField txtCustomerFirstName;
    private javax.swing.JTextField txtCustomerID;
    private javax.swing.JTextField txtCustomerLastName;
    private javax.swing.JTextField txtCustomerLegalName;
    private javax.swing.JTextField txtCustomerMiddleName;
    private javax.swing.JTextField txtCustomerNationalIDNumber;
    private javax.swing.JTextField txtCustomerVATID;
    // End of variables declaration//GEN-END:variables
}
