/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package invoiceGenerator.view.viewUtil;
import invoiceGenerator.controller.CustomerHandler;
import invoiceGenerator.model.Customer;
import invoiceGenerator.util.InvoiceGeneratorException;

import javax.swing.*;
import java.util.List;

/**
 *
 * @author tnebes
 */
public class CustomerPicker extends javax.swing.JFrame {

    private CustomerHandler customerHandler;

    /**
     * Creates new form CustomerPicker
     */
    public CustomerPicker() {
        this.customerHandler = new CustomerHandler();
        initComponents();
        initCustomers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstCustomerList = new javax.swing.JList<>();
        btnChoose = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtCustomerPickerSearch = new javax.swing.JTextField();
        btnCustomerPickerSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        lstCustomerList.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                lstCustomerListComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(lstCustomerList);

        btnChoose.setText("Choose");
        btnChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtCustomerPickerSearch.setText("search...");

        btnCustomerPickerSearch.setText("Search!");
        btnCustomerPickerSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerPickerSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnChoose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCustomerPickerSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCustomerPickerSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCustomerPickerSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCustomerPickerSearch))
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCancel)
                    .addComponent(btnChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseActionPerformed
        triggerCustomerCollection();
    }//GEN-LAST:event_btnChooseActionPerformed


    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void lstCustomerListComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lstCustomerListComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_lstCustomerListComponentShown

    private void btnCustomerPickerSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerPickerSearchActionPerformed
        if (txtCustomerPickerSearch.getText().isBlank()) {
            initCustomers();
            return;
        }
        updateCustomerList(txtCustomerPickerSearch.getText());
    }//GEN-LAST:event_btnCustomerPickerSearchActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChoose;
    private javax.swing.JButton btnCustomerPickerSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Customer> lstCustomerList;
    private javax.swing.JTextField txtCustomerPickerSearch;
    // End of variables declaration//GEN-END:variables

    private void initCustomers() {
        DefaultListModel<Customer> customers = new DefaultListModel<>();
        try {
            customers.addAll(customerHandler.getData());
        } catch (InvoiceGeneratorException e) {
            e.printStackTrace();
        }
        lstCustomerList.setModel(customers);
    }

    public Customer returnChosenCustomer() {
        Customer selectedCustomer = lstCustomerList.getSelectedValue();
        return selectedCustomer;
    }

    private void triggerCustomerCollection() {
        Customer newCustomer = returnChosenCustomer();
        if (newCustomer != null) {
            this.dispose();
            return;
        }
        JOptionPane.showMessageDialog(rootPane, "No customer selected.");
    }

    public interface CustomerReturner {
        void run(Customer customer);
    }

    public void giveMeCustomer(CustomerReturner customerReturner) {
        btnChoose.addActionListener(e ->
            customerReturner.run(returnChosenCustomer())
        );
    }

    private void updateCustomerList(String text) {
        DefaultListModel<Customer> listCustomers = new DefaultListModel<>();
        try {
            List<Customer> searchResult = customerHandler.getData(text);
            listCustomers.addAll(searchResult);
            lstCustomerList.setModel(listCustomers);
        } catch (InvoiceGeneratorException e) {
            e.printStackTrace();
        }
    }

}
